### ISSUE TITLE
clarify whether this is a fork or the new upstream for this campaign

### ISSUE THREAD

**Issue by cooljeanius** [nemaara/A_New_Order#1]
I have my own fork of A New Order that I'm working on, and, once I'm done with it, I'd like to know whether this is the correct place to submit my changes, or if szopen has his own repository somewhere. My fork is here, btw: https://github.com/cooljeanius/A_New_Order

**Comment by nemaara** [comment]
Yes you can submit your changes here and I'll see about putting them in.

**Comment by cooljeanius** [comment]
ok, I see it managed to handle the fact that I already had a repository by this name when forking it; it just appended a "`-1`" to the end: https://github.com/cooljeanius/A_New_Order-1 
I think I'll continue making the changes in my original repository for now, though, and only use the second one when it comes time to submit a pull request... (I want to finish a second playthru before doing that)

**Comment by cooljeanius** [comment]
I am still going to keep this open because there should be a note in the README or something

**Comment by cooljeanius** [comment]
I included a README update in PR #2, so I'm closing this now
