### ISSUE TITLE
Infinite increasing amount of gold for the outlaw in S08 on Nightmare

### ISSUE THREAD

**Issue by Toranks** [nemaara/A_New_Order#106]
This variable grows by 1 every time you kill a unit, so killing an enemy unit gives the enemy number of enemies killed+1 EVERY TIME. This makes this stage on impossible, really impossible, no matter what you do you will be overwhelmed sooner or later. (Now for example he is receiving 50+ gold every kill for me)

https://github.com/nemaara/A_New_Order/blob/d4c0d747bf0b413d6ac55367d61eeff95e9e9126/scenarios/08_Outlaw_Base.cfg#L253

I think the intention was {VARIABLE ano_roe_tmp 5} instead of {INCREMENT ano_roe_tmp}, so the enemy receives 5 gold every kill. It's still a lot of money and it would be a nightmare, but maybe it's possible.

Although it doesn't seem fair to me that he receives money every time you kill, it is better that he has a higher starting amount and that the first part of the battle is in the woods, and not in the water (because the outlaw takes a long time to get his units out and it gives me time to surround him with my best units on the bridges), and the second part of the battle takes place in the water and swamps surrounding the fortress, when you have managed to wear down the enemy.

**Comment by Toranks** [comment]
Played the scenario with the change I suggested before, my new suggestion is in addition to change {VARIABLE ano_roe_tmp 5} (so the enemy will receive 5 gold per victim), start the scenario for the outlaws with 200 or 250 gold instead of 170
Line 51:          {GOLD4 90 110 140 200}

**Comment by cooljeanius** [comment]
so, the NIGHTMARE difficulty is basically supposed to be "only beatable by @Hejnewar" mode, so I'd like to see if it's too hard for him too. 

> Line 51: {GOLD4 90 110 140 200}
I would prefer to keep this relationship linear if possible

**Comment by cooljeanius** [comment]
ok does my fix in cooljeanius/A_New_Order@015a369 look ok? I haven't tested it yet...

**Comment by cooljeanius** [comment]
> ok does my fix in [cooljeanius/A_New_Order@015a369](https://github.com/cooljeanius/A_New_Order/commit/015a369) look ok? I haven't tested it yet...

ok this was merged as part of #109; I'm going to consider this fixed now. Feel free to reopen if it's still too much.
