### ISSUE TITLE
Akladian Homeguard line: mismatch between sound effects, damage type, graphics, and description

### ISSUE THREAD

**Issue by cooljeanius** [nemaara/A_New_Order#11]
With the Akladian Homeguard line (Homeguard/Shieldguard/Protector), they all deal impact damage, but sometimes the sound effect and/or graphic for their attack looks/sounds like a blade. Ideally things should be brought in sync. Including the text in their unit info.

**Comment by cooljeanius** [comment]
@knyghtmare if PR #13 is merged, will that be enough to close this?

**Comment by nemaara** [comment]
Should be fixed by PR #13.
