### ISSUE TITLE
Useless spanish translation

### ISSUE THREAD

**Issue by Toranks** [nemaara/A_New_Order#111]
As I progress through the game the translation gets worse and worse, to the point of saying things that have nothing to do with it. I would recommend that in the next update you completely deactivate the translation except what I sent in my PR, waiting for it to be done correctly. It'll take a few months, but I'm almost done with Era of Magic. I also have to update the one for Eastern Invasion Revised to the latest version.

**Comment by cooljeanius** [comment]
(this counts as a more-specific example of issue #10 btw; I'm sure some of the other translations are probably like this, too...)

**Comment by Toranks** [comment]
This branch will close this in the future:
https://github.com/Toranks/A_New_Order/tree/translation-second-pr
