### ISSUE TITLE
Name to basic healing skill learned on S14b

### ISSUE THREAD

**Issue by Toranks** [nemaara/A_New_Order#112]
Suggestion:

14b_Bontom line 33
```
id=basic_healing
name= _ "basic healing"
```

**Comment by cooljeanius** [comment]
huh I'm surprised we didn't already have that; I'll give it a check once I get up to that scenario...

**Comment by cooljeanius** [comment]
also note that the ability exists in 2 places in the file; there's another copy of it at lines 1000-1009 near the bottom of the file
(I'm actually not quite sure which of the 2 actually gets used...)

**Comment by Toranks** [comment]
Both are used. One is for Gawen and the others for the other non-Akladians units.
What I suggest is to change the name= _"heals +2, cures poison" to a name that doesn't occupy as much in the traits, and move heals+2, cure to description=_"heals +2, cures poison"

**Comment by cooljeanius** [comment]
so, like I did in cooljeanius/A_New_Order@821df8d?

**Comment by cooljeanius** [comment]
ok so yeah I tested that and it looks fine; I'll include it in my next PR

**Comment by cooljeanius** [comment]
PR #117 ought to close this

**Comment by cooljeanius** [comment]
Fixed in [e439458](https://github.com/nemaara/A_New_Order/commit/e439458b3985368508d674d1079c365dc51431ed)
