### ISSUE TITLE
Enable optional advancements?

### ISSUE THREAD

**Issue by cooljeanius** [nemaara/A_New_Order#118]
Mainline's [optional_unit_advancements.cfg](https://github.com/wesnoth/wesnoth/blob/master/data/core/macros/optional_unit_advancements.cfg) contains a bunch of optional advancements that we could enable: https://www.wesnoth.org/macro-reference.html#file:optional_unit_advancements.cfg

Friendly ones:
- `{ENABLE_PARAGON}` (so Majid Yahyazad can finally turn into @knyghtmare)
- `{ENABLE_WOSE_SHAMAN}` (only relevant if/when #117 gets merged, and even then I doubt any allied woses would live that long...)

Hostile ones:
- `{ENABLE_ARMAGEDDON_DRAKE}` (only relevant if/when #117 gets merged, and even then I doubt any enemy drakes would live that long...)
- `{ENABLE_NIGHTBLADE}`
- `{ENABLE_TROLL_SHAMAN}`
- `{ENABLE_ANCIENT_LICH}`
- `{ENABLE_DEATH_KNIGHT}`

So, what do people think? Does it make sense to enable any of these? Perhaps only on certain difficulty levels?

**Comment by cooljeanius** [comment]
@Toranks @nemaara any opinions?

**Comment by nemaara** [comment]
For me, it's not necessary to enable any but I leave it to you.

**Comment by Toranks** [comment]
It doesn't hurt, but I think the campaign is not long enough to enjoy those advances

**Comment by cooljeanius** [comment]
ok I think I'll try enabling them for 1.7.0, just to see how that goes...

**Comment by cooljeanius** [comment]
PR #171 will close this.
