### ISSUE TITLE
Fix wrong ellipses

### ISSUE THREAD

**Issue by cooljeanius** [nemaara/A_New_Order#15]
Reme maintains his spiky "hero" even after he stops being necessary to keep alive. Meanwhile, other units that are necessary to keep alive don't get the spiky "hero" ellipse (e.g. Deorien). Also I think Rob Roe has the wrong crown thingy under his orb... I can fix some of these myself, but not all of them...
Edit: making a checklist:
- [x] ~~Rob Roe looks like a hero, but isn't~~
- [x] ~~Deorien is a hero, but doesn't look like one~~
- [ ] Need to use `{UNMAKE_HERO}` on Reme at some point

**Comment by cooljeanius** [comment]
PR #17 addresses Deorien and Rob Roe's ellipses; Rob Roe's isn't tested yet though. Also I still need to figure out where to put a call to `{UNMAKE_HERO}` on Reme...

**Comment by cooljeanius** [comment]
> Also I still need to figure out where to put a call to `{UNMAKE_HERO}` on Reme...

The 2 main choices are: S06, "Separation" (right before he leaves), or S14b, "Bontom" (when you get him back)

**Comment by nemaara** [comment]
Doesn't matter to me. Either could work I guess.

**Comment by cooljeanius** [comment]
ok I went with the former in cooljeanius/A_New_Order@264a8d3

**Comment by cooljeanius** [comment]
> ok I went with the former in [cooljeanius/A_New_Order@264a8d3](https://github.com/cooljeanius/A_New_Order/commit/264a8d3)

...which is now PR #43 (I'll check the associated checkbox off once it's merged)
