### ISSUE TITLE
bug - S2 assassin spawns even if S1 assassin got interrogated

### ISSUE THREAD

**Issue by ForestDragon-wesnoth** [nemaara/A_New_Order#178]
S2 assassin spawns even if S1 assassin got interrogated and killed

**Comment by cooljeanius** [comment]
I haven't ever seen this happen myself, so this will require some further investigation...

**Comment by cooljeanius** [comment]
The assassin's appearance in S2 is only supposed to happen if `ano_assa_killed` is set to `no`, and that variable is supposed to get set to `yes` in all of his possible deaths, so I really don't see how this could happen...

**Comment by ForestDragon-wesnoth** [comment]
tried it again, it worked properly this time. strange. I guess we can close this for now.

**Comment by cooljeanius** [comment]
ok, feel free to reopen if you see it happen again and can reproduce it.
