### ISSUE TITLE
idea - Lorin melee change

### ISSUE THREAD

**Issue by ForestDragon-wesnoth** [nemaara/A_New_Order#179]
on lvl1 Lorin has a 5-strike attack, but on lvl2-3 her attack is a 4-strike one, even though it's much stronger but still
current progression is 5-5 > 11-4 > 13-4
maybe something like 5-5 > 8-5 > 11-5 would make more sense

**Comment by cooljeanius** [comment]
I think the current setup is due to her AMLAs that increase the strike count... @nemaara WDYT?

**Comment by nemaara** [comment]
maybe lvl 1 should be 6-4 or sth?

**Comment by cooljeanius** [comment]
> maybe lvl 1 should be 6-4 or sth?

Yeah, I guess that could work... I kinda wish we could confirm with szopen first as to whether the existing RiPLiB violation is intentional or not (maybe to represent Lorin aging?), but he hasn't really been seen lately...

**Comment by nemaara** [comment]
Gameplay over lore always.

**Comment by ForestDragon-wesnoth** [comment]
> Yeah, I guess that could work... I kinda wish we could confirm with szopen first as to whether the existing RiPLiB violation is intentional or not (maybe to represent Lorin aging?), but he hasn't really been seen lately...

considering she regains a 5-th strike via AMLA, that seems unlikely

**Comment by cooljeanius** [comment]
ok, so I'll try making the "6-4 for L1" change and test that in my next playthru...

**Comment by cooljeanius** [comment]
one thing I remembered when testing cooljeanius/A_New_Order@b42b801 is that I gave Lorin the "Strong" trait on EASY, so it's actually 7-4 there...

**Comment by cooljeanius** [comment]
#194 ought to close this.
