### ISSUE TITLE
In Outlaw Base Ruvio calling Gawen "Gawen".

### ISSUE THREAD

**Issue by alxrem** [nemaara/A_New_Order#182]
In "Outlaw Base" scenario Ruvio saying "You see, Gawen, when the royal family of Wesnoth started a war over succession..."

Shouldn't he call nim "Haldric"?

**Comment by alxrem** [comment]
Right before this, "Ally from Past" ends with the speech "... I want everyone to swear they won't tell anyone that this man is the rightful king of Vakladia, Gawen Hagarthen. He is just 'Haldric' now...."

**Comment by cooljeanius** [comment]
Yeah, looking at the context, it looks like they're just talking to each other at that point, and haven't noticed that Rob Roe is there yet, and still think that the place is abandoned, so I think they might have let their guard down at that point... let's see what @nemaara thinks, though...

**Comment by nemaara** [comment]
Yeah it's prob better to refer to him as Haldric there.

**Comment by cooljeanius** [comment]
> Yeah it's prob better to refer to him as Haldric there.

OK, I'll include that in my next PR

**Comment by alxrem** [comment]
While the issue is not closed, take a look to the similar phrases:

- 16 Choosing the best
	      {MSG_Ruvio _"Wait a minute. Your father, Gawen, married Lorin after the death of your mother, didn't he?"}
	      {MSG_Ruvio _"My, what a wonderful culture you have. But we can speak on this later. Now, Gawen, choose the eighteen very best troops to take along with us."}
- 17 Sneaking out the Raedwood
	      {MSG_Ruvio _"Gawen, I thought I told you to keep your identity a secret."}
	      {MSG_Ruvio _"Well, Gawen, which path will you take? The stealthy route I proposed, or the violent route proposed by your stepmother?"}
- 19a The Woods Of Okladia, 19b Entering Okladia
	      {MSG_Ruvio _"We'd better get hurrying, Gawen! If we don't make it to the signpost in time, reinforcements could arrive and trap us!"}

**Comment by cooljeanius** [comment]
> While the issue is not closed, take a look to the similar phrases:
> 
>     * 16 Choosing the best
>       {MSG_Ruvio _"Wait a minute. Your father, Gawen, married Lorin after the death of your mother, didn't he?"}
>       {MSG_Ruvio _"My, what a wonderful culture you have. But we can speak on this later. Now, Gawen, choose the eighteen very best troops to take along with us."}
> 
>     * 17 Sneaking out the Raedwood
>       {MSG_Ruvio _"Gawen, I thought I told you to keep your identity a secret."}
>       {MSG_Ruvio _"Well, Gawen, which path will you take? The stealthy route I proposed, or the violent route proposed by your stepmother?"}
> 
>     * 19a The Woods Of Okladia, 19b Entering Okladia
>       {MSG_Ruvio _"We'd better get hurrying, Gawen! If we don't make it to the signpost in time, reinforcements could arrive and trap us!"}

Hm... @nemaara do you agree on all of these? In S08 it made sense to change it since it was immediately after Ruvio had just said to starting using "Haldric", but:
- In S16 they're solely among allies, with no need to worry about enemies overhearing them
- In S17, one of those is immediately after Gawen has revealed his identity anyways, so there's no need to keep up the charade
- In S19, maybe it's been long enough that he's forgotten?

**Comment by nemaara** [comment]
Some of them even read awkwardly with his name to me but yeah I agree with you that they probably aren't needed. only the last one to change if you like
