### ISSUE TITLE
Lorin's phrase about bridges in Orannon

### ISSUE THREAD

**Issue by alxrem** [nemaara/A_New_Order#187]
In the "Orannon" scenario all units ask Gawen about bridge: "Milord, should I destroy this bridge?". In this scenario Lorin and Gawen communicate as mother and son. Could be better to use for Lorin different phrase in this case?

**Comment by cooljeanius** [comment]
Good point; I noted some similar situations in issue #27, but not the one with Lorin specifically...

**Comment by cooljeanius** [comment]
(kinda waiting for #171 to get merged before I start on this; I want to do a whole new playthrough, so this would probably come at the end...)
