### ISSUE TITLE
Update credits

### ISSUE THREAD

**Issue by cooljeanius** [nemaara/A_New_Order#28]
There have been new contributions that should be noted, and Wesnoth 1.16 fixes the bug where BfW crashes on credits that are too long, so the credits should be updated when porting to that version.

**Comment by cooljeanius** [comment]
celmin and Pent deserve credits entries, too, I think

**Comment by cooljeanius** [comment]
Also, the change in the way the credits get displayed between 1.14 and 1.16 might mean we want to rewrite some of them...

**Comment by CelticMinstrel** [comment]
…what would I be credited for, exactly?

**Comment by cooljeanius** [comment]
> …what would I be credited for, exactly?

WML Assistance / "Additional thanks to"

**Comment by cooljeanius** [comment]
> > …what would I be credited for, exactly?
> 
> WML Assistance / "Additional thanks to"

(I think it was your help that allowed me to fix bug #39 on my end, for instance)

**Comment by cooljeanius** [comment]
#76 will close this

**Comment by cooljeanius** [comment]
Done in [e2cca67](https://github.com/nemaara/A_New_Order/commit/e2cca67e26975a26f327b7fcaaa1e9b708a0cf58)
