### ISSUE TITLE
Should Gawen have traits?

### ISSUE THREAD

**Issue by cooljeanius** [nemaara/A_New_Order#37]
This isn't really so much a bug report as it is a discussion question: does it make sense for Gawen to have traits or not? It feels kinda weird how he doesn't have any currently, but then again, on second thought, that kinda makes sense from a story POV: throughout most of the beginning of the campaign, he's trying not to be who he is, and thus is avoiding displaying any notable traits. It's only later once he experiences character growth and accepts his role that he starts to display personality. Also, from a gameplay POV, I'm not really sure Gawen needs anything; usually when one of my heroes dies, it's one of my other ones, and I usually manage to get Gawen to level 3 (plus an AMLA or two) by the end of the campaign. So, while he might not technically *need* any traits, that blank space in the sidebar where traits ought to go does still kinda bug me...

**Comment by cooljeanius** [comment]
I messaged szopen about this one and he said it'd be ok to give Gawen traits, but didn't suggest any particular ones... maybe I could do a sort of RPG mechanic where the player gets to choose his traits? I think I've seen some other UMC where they start the game off by prompting the player to choose traits for their hero...

**Comment by cooljeanius** [comment]
> ...maybe I could do a sort of RPG mechanic where the player gets to choose his traits? I think I've seen some other UMC where they start the game off by prompting the player to choose traits for their hero...

ok yeah in "A Group In A War" there's `utils/traits.cfg` that we could cannibalize from; it'd require some modification to work here, though...

**Comment by cooljeanius** [comment]
Related: @Ashmyr's wesnoth/wesnoth#7129

**Comment by nemaara** [comment]
Okay based on octalot's comment on one of those PRs along the lines of it being better for units to match up to their encyclopedia stats if possible (which I agree with), I think the answer to this is no.
