### ISSUE TITLE
Uri van Roe weird behavior in S4

### ISSUE THREAD

**Issue by nemaara** [nemaara/A_New_Order#46]
@cooljeanius Your code here doesn't behave how you might think it does: https://github.com/nemaara/A_New_Order/blob/fb1f2579862e2324dc5c36beb69774cacae62219/scenarios/04_Battle_of_Barnon.cfg#L539. 

Turns out you can make him run between your keep and his own so he gets stuck in limbo and doesn't recruit again. Makes the scenario a lot easier to just defend forever.

**Comment by cooljeanius** [comment]
ok so I guess #30 isn't actually fixed after all... I wonder if this is a general issue with the `[leader_goal]` tag, or just how it's being used here?

**Comment by cooljeanius** [comment]
maybe it's worth trying setting some of the other keys that the `[leader_goal]` tag accepts? e.g. `auto_remove=`, `id=`, and/or `max_risk=`... or maybe adding a `[micro_ai]` tag?

**Comment by nemaara** [comment]
Yea your code does exactly what you're telling him to do. The problem is the logic is flawed. By setting a leader goal only when someone is on the keep, all I have to do is make Gawen or any other unit run on and off the keep and Uri will just run back and forth. So it needs some better logic to either go straight there and charge into you or to just stay at his base permanently. No waffling back and forth lol.

**Comment by cooljeanius** [comment]
Oh you mean this part:
https://github.com/nemaara/A_New_Order/blob/fb1f2579862e2324dc5c36beb69774cacae62219/scenarios/04_Battle_of_Barnon.cfg#L547-L567
That's different from the setting of the `[leader_goal]` here:
https://github.com/nemaara/A_New_Order/blob/fb1f2579862e2324dc5c36beb69774cacae62219/scenarios/04_Battle_of_Barnon.cfg#L215-L230
Also the event from L547-L567 only ought to fire once, on turn 15, not every time Gawen moves on or off the keep. If Uri keeps waffling about which way he wants to go, that's got to be decisions made by his AI instead.

**Comment by nemaara** [comment]
Hmmm. You're right so that means the AI probably needs some tweaking. Can't release without this fixed I think.

**Comment by cooljeanius** [comment]
> Hmmm. You're right so that means the AI probably needs some tweaking. Can't release without this fixed I think.

I'm busy tomorrow, but I should be able to get around to testing [13dfd3c](https://github.com/cooljeanius/A_New_Order/commit/13dfd3c501de708a4630df8a84f2567443969502) sometime within the next week or so...

**Comment by cooljeanius** [comment]
OK I've tested some changes, and... I'm getting kind of tired testing this scenario, tbh; can I just submit a PR for what I've got so far and leave the rest of the testing to you?

**Comment by nemaara** [comment]
Sure thing!

**Comment by cooljeanius** [comment]
> Sure thing!

ok I opened PR #49

**Comment by cooljeanius** [comment]
so, did merging PR #49 fix this satisfactorily?

**Comment by nemaara** [comment]
Yeah seems fine.

**Comment by cooljeanius** [comment]
We might need to reopen; @knyghtmare discovered another oddity with this

**Comment by cooljeanius** [comment]
Yeah I'm reopening this; szopen sent me a message on the forums with a replay from another player who was able to kill Uri because of this; I'm attaching it here:
[ANO-Battle of Barnon Turn 21.gz](https://github.com/nemaara/A_New_Order/files/8840672/ANO-Battle.of.Barnon.Turn.21.gz)

**Comment by cooljeanius** [comment]
ok so #76 should do a better job of addressing this (not necessarily "fixing" it *per se*, just making the effects of it more manageable to the point where this can be closed again)

**Comment by cooljeanius** [comment]
OK hopefully [e2cca67](https://github.com/nemaara/A_New_Order/commit/e2cca67e26975a26f327b7fcaaa1e9b708a0cf58) can count as closing this for real this time; it might still require some further tuning, though...
