### ISSUE TITLE
Better fallback code for cases of players killing enemy leaders that they shouldn't

### ISSUE THREAD

**Issue by cooljeanius** [nemaara/A_New_Order#52]
So IMO the messages that you're not supposed to kill Bor Cryne and Uri van Roe in S04 still aren't quite enough; there remains the possibility that the player won't actually stop what they are doing, in which case, what happens then? The player could theoretically just keep playing forever without actually reaching an end to the scenario... see further feedback from @knyghtmare on Discord...

**Comment by cooljeanius** [comment]
> see further feedback from @knyghtmare on Discord...

some ideas: <img width="1221" alt="Screen Shot 2022-04-23 at 11 58 27" src="https://user-images.githubusercontent.com/1388660/164913694-f495a799-b2b3-401e-8181-2543ef27cf50.png">

**Comment by cooljeanius** [comment]
@CelticMinstrel suggests making it an achievement

**Comment by CelticMinstrel** [comment]
Or I would, if we had a system for that yet.

**Comment by cooljeanius** [comment]
well, maybe something you get points for in the final tally (S30, "Final")...

**Comment by cooljeanius** [comment]
#76 ought to fix this

**Comment by cooljeanius** [comment]
OK this ought to be closed now by [e2cca67](https://github.com/nemaara/A_New_Order/commit/e2cca67e26975a26f327b7fcaaa1e9b708a0cf58)
