### ISSUE TITLE
`_server.pbl` updates 

### ISSUE THREAD

**Issue by cooljeanius** [nemaara/A_New_Order#56]
<img width="1792" alt="Screen Shot 2022-05-05 at 22 01 05" src="https://user-images.githubusercontent.com/1388660/167054642-8c8580e5-e1a5-4b17-b478-c2541db951de.png">
The "author" field still says "szopen" even though he is no longer working on it. I'm not saying to remove him entirely from that field, though, just maybe to rephrase it as "szopen (original), egallager and nemaara (current)" or something. Also the description could be updated a bit; linking to the forum thread in the description is redundant when there's already a separate field for a link to the forum thread. Maybe put a link to this GitHub repo there instead?

**Comment by cooljeanius** [comment]
Oh, and some entries for the "Tags" field would be nice, too

**Comment by cooljeanius** [comment]
(this is something that @nemaara will have to do, since `_server.pbl` isn't stored in the repository...)

**Comment by nemaara** [comment]
Personally I prefer leaving szopen as the author and having us as maintainers in the description. I don't feel that I've done any real intellectual or gameplay work on the campaign outside of just supporting it. If you think you've made a significant enough contribution outside of code maintenance and bugs I'll go ahead and add you when uploading.

**Comment by cooljeanius** [comment]
> Personally I prefer leaving szopen as the author and having us as maintainers in the description. I don't feel that I've done any real intellectual or gameplay work on the campaign outside of just supporting it. If you think you've made a significant enough contribution outside of code maintenance and bugs I'll go ahead and add you when uploading.

Either the author field or the description field is fine; whichever works for you.

**Comment by cooljeanius** [comment]
ok the author part of this is fixed as of 1.5.0; I guess I could keep this open for the part about the link in the description, too, but actually nah, let's close it.
