### ISSUE TITLE
Fill in GitHub repository info here

### ISSUE THREAD

**Issue by cooljeanius** [nemaara/A_New_Order#58]
Specifically, the "Description", "Website", and "Topics" fields. Compare [my version of the repo](https://github.com/cooljeanius/A_New_Order) (not the one forked from this one, but rather the separate one):
<img width="320" alt="Screen Shot 2022-05-06 at 17 42 26" src="https://user-images.githubusercontent.com/1388660/167220287-1304dd56-9358-4fd1-a051-2b43f5261006.png">

**Comment by cooljeanius** [comment]
As with #56 this is something that only @nemaara can do

**Comment by cooljeanius** [comment]
Oh, setting a social card under "Settings" would be nice, too:
<img width="794" alt="Screen Shot 2022-05-28 at 19 24 45" src="https://user-images.githubusercontent.com/1388660/170845860-ed8d32b3-12a1-44c3-b451-8713e6360ed9.png">
I used this for mine: https://github.com/cooljeanius/ANO_art/blob/main/wprawki/logo/logo-social.png

**Comment by cooljeanius** [comment]
Hm, so I have push access to this repository now, but it looks like that doesn't include permissions for editing the info... I can assign @nemaara now though.

**Comment by nemaara** [comment]
Done!

**Comment by cooljeanius** [comment]
> Done!

Thanks!
