### ISSUE TITLE
`{CHECK_EVEN}`/`{IF_EVEN}`/`{IF_ODD}` macros are broken

### ISSUE THREAD

**Issue by cooljeanius** [nemaara/A_New_Order#70]
So, I first noticed this when trying to use the macros in S04 (Battle of Barnon), but it's a more generic issue than that if you look at how the macros are actually implemented:
https://github.com/nemaara/A_New_Order/blob/507890a131f5defd6e55ca0179292a64fadb643e/macros/programming-macros.cfg#L277-L303
I mean, seriously? Why did szopen do it like that? Why not just use a modulo?

**Comment by soliton-** [comment]
Well, modulo support was added at the end of 2006 and ANO was first published in mid 2005.

**Comment by Elvish-Hunter** [comment]
A quick search shows that `{IF_ODD}` and `{IF_EVEN}` are used only in one scenario and `{CHECK_EVEN}` is just a dependency for these two macros.
If that's OK, I'll prepare a small pull request to update this ancient code.

**Comment by cooljeanius** [comment]
> A quick search shows that `{IF_ODD}` and `{IF_EVEN}` are used only in one scenario and `{CHECK_EVEN}` is just a dependency for these two macros. If that's OK, I'll prepare a small pull request to update this ancient code.

It's definitely okay; please do!

**Comment by cooljeanius** [comment]
I confirmed that #121 fixes this; thanks @Elvish-Hunter for the PR!
