### ISSUE TITLE
In last battle Gawen asks himself if he should destroy a bridge

### ISSUE THREAD

**Issue by odanoburu** [nemaara/A_New_Order#82]
In the last scenario, any units coming near a bridge ask their commander if they should destroy it. This includes Gawen, which is fine since we actually are asking the player, but it should probably use different dialogue (it's a bit weird for Gawen to refer to himself as 'Milord'). Wesnoth 1.17.6, ANO 1.4.1

**Comment by cooljeanius** [comment]
This is kind of a more-specific instance of checkbox 2 in issue #27; it should at least be simpler to fix than what I was originally thinking about doing with that dialogue, though (all that needs to be done here is to add a check to see if the unit is Gawen or not)

**Comment by cooljeanius** [comment]
so I added a potential fix for this issue to my other version of this repo in [cooljeanius/A_New_Order@fcaeb7e](https://github.com/cooljeanius/A_New_Order/commit/fcaeb7ec8083a260941984480e2d8d17664bd52c); I haven't tested it yet, though... hey @nemaara remind me to open a PR for this after merging PR #80 and then it'd probably be a good time for us to cut a new release; it's been awhile now...

**Comment by cooljeanius** [comment]
ok PR #83 should fix this (once merged)

**Comment by cooljeanius** [comment]
> ok PR #83 should fix this (once merged)

ok that's merged, so this should be fixed now
