### ISSUE TITLE
Lvl 1 Akladian Warrior advances to Lvl 1 Akladian Leader

### ISSUE THREAD

**Issue by cooljeanius** [nemaara/A_New_Order#9]
Originally reported by @knyghtmare on the forums. This breaks the `units.wesnoth.org`display; note how Akladian Warriors aren't visible on it: https://units.wesnoth.org/1.14/A_New_Order/en_US/A_New_Order.html 
The advancement path may very well have been szopen's original intention (or not; we don't know), but I think this does in fact count as a bug due to the way it breaks the `u.w.o.` display. I have no idea how to fix it, though.

**Comment by knyghtmare** [comment]
> I have no idea how to fix it, though.

Alkadian Leader should advance from Clansman
Alkadian Warrior can advance to the Alkadian Chieftain.

Do note that this causes a powercreep so Alkadian leader units won't be that much used, as Raider, Homeguard and Warrior seem better.

**Comment by oo13** [comment]
> The advancement path may very well have been szopen's original intention (or not; we don't know)

szopen said about the advancement into leader at July 11, 2005.

> Warrior now can turn into leader (the same level, but with different prospects in future. It may change in later releases)

https://forums.wesnoth.org/viewtopic.php?f=8&t=6486&start=15

**Comment by cooljeanius** [comment]
> > The advancement path may very well have been szopen's original intention (or not; we don't know)
> 
> szopen said about the advancement into leader at July 11, 2005.
> 
> > Warrior now can turn into leader (the same level, but with different prospects in future. It may change in later releases)
> 
> https://forums.wesnoth.org/viewtopic.php?f=8&t=6486&start=15

"It may change" but in what manner, I wonder?

**Comment by cooljeanius** [comment]
> > I have no idea how to fix it, though.
> 
> Alkadian Leader should advance from Clansman
> Alkadian Warrior can advance to the Alkadian Chieftain.
> 
> Do note that this causes a powercreep so Alkadian leader units won't be that much used, as Raider, Homeguard and Warrior seem better.

That seems fair, tbh, as leaders are supposed to be rarer than the other units...

**Comment by knyghtmare** [comment]
> > > I have no idea how to fix it, though.
> > 
> > 
> > Alkadian Leader should advance from Clansman
> > Alkadian Warrior can advance to the Alkadian Chieftain.
> > Do note that this causes a powercreep so Alkadian leader units won't be that much used, as Raider, Homeguard and Warrior seem better.
> 
> That seems fair, tbh, as leaders are supposed to be rarer than the other units...

Unless there is a level 4 available with leadership, this ability is a useless thing in late game
same for Intelligent trait. One other suggestion would be to move the Alkadian leader line from 1,2,3 to 2,3,4 but it may cause high imbalance.

Therefore my first suggestion seems more appropriate.

**Comment by cooljeanius** [comment]
I'd like to get @nemaara's opinion on this

**Comment by nemaara** [comment]
I agree, Knyght's first suggestion seems better, and then you can choose to buff leader units a little bit.

**Comment by cooljeanius** [comment]
> I agree, Knyght's first suggestion seems better, and then you can choose to buff leader units a little bit.

ok, I'll test this out after I finish up the stuff I'm working on for TEG (unless someone else wants to beat me to the punch)

**Comment by cooljeanius** [comment]
> > I agree, Knyght's first suggestion seems better, and then you can choose to buff leader units a little bit.
> 
> ok, I'll test this out after I finish up the stuff I'm working on for TEG (unless someone else wants to beat me to the punch)

so, I didn't actually finish the TEG stuff (just taking a break because I got stuck), but anyways I opened PR #12 to address this

**Comment by cooljeanius** [comment]
since PR #12 has been merged I guess this can be closed? Or are we waiting until someone's done another balance pass in response to how the new advancement paths work?

**Comment by cooljeanius** [comment]
> since PR #12 has been merged I guess this can be closed? Or are we waiting until someone's done another balance pass in response to how the new advancement paths work?

After another playthru, I think the new advancement paths are fine.

**Comment by cooljeanius** [comment]
> After another playthru, I think the new advancement paths are fine.

...so that means, that at this point, the only thing remaining for this bug to be closed is for PR #17 to be merged

**Comment by cooljeanius** [comment]
oh, one other thing: the changes for this issue have broken savefile compatibility with old replays... do we want to do something to address that?

**Comment by nemaara** [comment]
I don't intend to, but you can try if you like.

**Comment by cooljeanius** [comment]
> I don't intend to, but you can try if you like.

ok so I don't really know how I would, so now that the PR is merged, I guess I'll just close this.
cc @knyghtmare

**Comment by cooljeanius** [comment]
> oh, one other thing: the changes for this issue have broken savefile compatibility with old replays... do we want to do something to address that?

(this is what prompted me to open wesnoth/wesnoth#6150 btw)
